title: David Ruhe
name: David Ruhe
user_description: Ph.D. Student in Machine Learning
# notes_url: "https://notenote.link.netlify.app"
# profile_pic: /assets/img/CrhnTql4_400x400.jpeg
# profile_pic: /assets/img/CrhnTql4_400x400.jpeg
profile_pic: /assets/img/1678012147461.jpeg
# profile_pic: /assets/img/PASFOTO.jpg
favicon: /assets/img/favico.png
copyright_name: MIT
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://davidruhe.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
encoding: utf-8
twitter: "https://twitter.com/djjruhe"
github: "https://github.com/DavidRuhe"
linkedin: "https://www.linkedin.com/in/david-ruhe-2a0a0b155"
scholar: "https://scholar.google.com/citations?user=JoXl9zUAAAAJ&hl=en&oi=ao"
email: "mailto:d.ruhe@uva.nl"

# Build settings
theme: null
plugins:
  - jekyll-feed 
  - jekyll-sitemap
  - jekyll-toc

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: null
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge


sass:
  style: compressed

collections:
    notes:
      output: true
      permalink: /notes/:title

toc:
  max_level: 3

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title
      content-type: post
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      content-type: notes
